        !COMPILER-GENERATED INTERFACE MODULE: Tue May 09 21:12:24 2017
        MODULE CREATE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CREATE_MODEL
            END SUBROUTINE CREATE_MODEL
          END INTERFACE 
        END MODULE CREATE_MODEL__genmod
