        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 08 21:00:42 2017
        MODULE READ_SGY_PARAMETER__genmod
          INTERFACE 
            SUBROUTINE READ_SGY_PARAMETER(MULIN_DAT,SAMPLE_POINT,       &
     &SAMPLE_RATE,FILE_SIZE,N_TRACE)
              CHARACTER(*) :: MULIN_DAT
              INTEGER(KIND=2) :: SAMPLE_POINT
              INTEGER(KIND=2) :: SAMPLE_RATE
              INTEGER(KIND=4) :: FILE_SIZE
              INTEGER(KIND=2) :: N_TRACE
            END SUBROUTINE READ_SGY_PARAMETER
          END INTERFACE 
        END MODULE READ_SGY_PARAMETER__genmod
