        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 08 21:00:42 2017
        MODULE READ_SGY_DATA__genmod
          INTERFACE 
            SUBROUTINE READ_SGY_DATA(MULIN_DAT,SAMPLE_POINT,N_TRACE,    &
     &SEISMIC_DATA)
              INTEGER(KIND=2) :: N_TRACE
              INTEGER(KIND=2) :: SAMPLE_POINT
              CHARACTER(*) :: MULIN_DAT
              REAL(KIND=4) :: SEISMIC_DATA(1:N_TRACE,1:SAMPLE_POINT)
            END SUBROUTINE READ_SGY_DATA
          END INTERFACE 
        END MODULE READ_SGY_DATA__genmod
