        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 08 21:00:42 2017
        MODULE READ_CMDFILE__genmod
          INTERFACE 
            SUBROUTINE READ_CMDFILE(CMDFILE,MULIN1_DAT,MULIN2_DAT,      &
     &OUTPUT_SGY_FILE)
              CHARACTER(*) :: CMDFILE
              CHARACTER(*) :: MULIN1_DAT
              CHARACTER(*) :: MULIN2_DAT
              CHARACTER(*) :: OUTPUT_SGY_FILE
            END SUBROUTINE READ_CMDFILE
          END INTERFACE 
        END MODULE READ_CMDFILE__genmod
