        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 08 21:00:42 2017
        MODULE WRITE_SGY_FILE__genmod
          INTERFACE 
            SUBROUTINE WRITE_SGY_FILE(OUTPUT_SGY_FILE,SAMPLE_POINT1,    &
     &SAMPLE_RATE1,N_TRACE1,SEISMIC_DATA1,SAMPLE_POINT2,SAMPLE_RATE2,   &
     &N_TRACE2,SEISMIC_DATA2)
              INTEGER(KIND=2) :: N_TRACE2
              INTEGER(KIND=2) :: SAMPLE_POINT2
              INTEGER(KIND=2) :: N_TRACE1
              INTEGER(KIND=2) :: SAMPLE_POINT1
              CHARACTER(*) :: OUTPUT_SGY_FILE
              INTEGER(KIND=2) :: SAMPLE_RATE1
              REAL(KIND=4) :: SEISMIC_DATA1(1:N_TRACE1,1:SAMPLE_POINT1)
              INTEGER(KIND=2) :: SAMPLE_RATE2
              REAL(KIND=4) :: SEISMIC_DATA2(1:N_TRACE2,1:SAMPLE_POINT2)
            END SUBROUTINE WRITE_SGY_FILE
          END INTERFACE 
        END MODULE WRITE_SGY_FILE__genmod
