        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 20 08:46:01 2017
        MODULE CREATE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CREATE_MODEL
            END SUBROUTINE CREATE_MODEL
          END INTERFACE 
        END MODULE CREATE_MODEL__genmod
