        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 22 09:31:23 2017
        MODULE READ_COORDINATE_SOURCE__genmod
          INTERFACE 
            SUBROUTINE READ_COORDINATE_SOURCE(INPUT_FILE_SOURCE,        &
     &X_COORDINATE_SOURCE,Z_COORDINATE_SOURCE)
              CHARACTER(*) :: INPUT_FILE_SOURCE
              REAL(KIND=4) :: X_COORDINATE_SOURCE
              REAL(KIND=4) :: Z_COORDINATE_SOURCE
            END SUBROUTINE READ_COORDINATE_SOURCE
          END INTERFACE 
        END MODULE READ_COORDINATE_SOURCE__genmod
