        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 26 20:06:19 2017
        MODULE CREATE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CREATE_MODEL
            END SUBROUTINE CREATE_MODEL
          END INTERFACE 
        END MODULE CREATE_MODEL__genmod
