        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 26 20:06:21 2017
        MODULE GRAPHER_SEISMOGRAMS__genmod
          INTERFACE 
            SUBROUTINE GRAPHER_SEISMOGRAMS(N_FILE,NLINE,VX_FILE,VZ_FILE)
              INTEGER(KIND=4) :: NLINE
              INTEGER(KIND=4) :: N_FILE
              CHARACTER(LEN=16) :: VX_FILE
              CHARACTER(LEN=16) :: VZ_FILE
            END SUBROUTINE GRAPHER_SEISMOGRAMS
          END INTERFACE 
        END MODULE GRAPHER_SEISMOGRAMS__genmod
