        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 26 20:06:21 2017
        MODULE OUTPUT_DATA__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_DATA(N_FILE,NLINE,SEISMOGRAM,TIME,V)
              INTEGER(KIND=4) :: NLINE
              INTEGER(KIND=4) :: N_FILE
              CHARACTER(*) :: SEISMOGRAM(1:N_FILE)
              REAL(KIND=4) :: TIME(1:NLINE,1:N_FILE)
              REAL(KIND=4) :: V(1:NLINE,1:N_FILE)
            END SUBROUTINE OUTPUT_DATA
          END INTERFACE 
        END MODULE OUTPUT_DATA__genmod
