        !COMPILER-GENERATED INTERFACE MODULE: Fri May 12 22:59:12 2017
        MODULE OPERATION_SGY__genmod
          INTERFACE 
            SUBROUTINE OPERATION_SGY(INPUT_SGY_FILE,OUTPUT_SGY_FILE)
              CHARACTER(*) :: INPUT_SGY_FILE
              CHARACTER(*) :: OUTPUT_SGY_FILE
            END SUBROUTINE OPERATION_SGY
          END INTERFACE 
        END MODULE OPERATION_SGY__genmod
