        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 21 16:49:05 2017
        MODULE SOURCE_FORCE__genmod
          INTERFACE 
            SUBROUTINE SOURCE_FORCE(FRE_WAVELET,DELAY_SOURCE_T0,TIME,FC0&
     &)
              REAL(KIND=4) :: FRE_WAVELET
              REAL(KIND=4) :: DELAY_SOURCE_T0
              REAL(KIND=4) :: TIME
              REAL(KIND=4) :: FC0
            END SUBROUTINE SOURCE_FORCE
          END INTERFACE 
        END MODULE SOURCE_FORCE__genmod
