        !COMPILER-GENERATED INTERFACE MODULE: Thu May 11 11:20:39 2017
        MODULE CREATE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CREATE_MODEL
            END SUBROUTINE CREATE_MODEL
          END INTERFACE 
        END MODULE CREATE_MODEL__genmod
