        !COMPILER-GENERATED INTERFACE MODULE: Thu May 04 10:22:52 2017
        MODULE CREATE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CREATE_MODEL
            END SUBROUTINE CREATE_MODEL
          END INTERFACE 
        END MODULE CREATE_MODEL__genmod
